import Head from "next/head";
import Cards from "../components/Cards";
import Modal from "../components/Modal";
import { useState } from "react";
import { useBudget } from "../contexts/BudgetContexts";
import ExpenseModal from "../components/ExpenseModal";
import TotalBudgetCard from "../components/TotalBudgetCard";
import ViewExpensesModal from "../components/ViewExpensesModal";

export default function Home() {
  //
  const [showModal, setShowModal] = useState(false);
  const [showViewModal, setShowViewModal] = useState(false);
  const [showExpenseModal, setShowExpenseModal] = useState(false);
  const [addExpenseModalBudgetId, setAddExpenseModalBudgetId] = useState();
  const [viewExpensesModalBudgetId, setViewExpensesModalBudgetId] = useState();
  const { budgets, getBudgetExpense } = useBudget();

  function openAddExpenseModal(budgetId) {
    setShowExpenseModal(true);
    setAddExpenseModalBudgetId(budgetId);
  }
  function openViewExpenseModal(budgetId) {
    setShowViewModal(true);
    setViewExpensesModalBudgetId(budgetId);
  }

  return (
    <>
      <div className="">
        <Head>
          <title>Budget Tracker</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="sticky top-0 z-50 flex justify-between bg-blue-600 p-5 items-center">
          <h1 className="text-xl text-white">BUDGET TRACKER</h1>
          <div className="">
            <button
              onClick={() => {
                setShowModal(true);
              }}
              className="text-white rounded bg-green-600/90 hover:bg-green-600 px-2 py-1 mr-3"
            >
              add budget
            </button>
          </div>
        </main>
        <div className="grid grid-flow-row-dense grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
          {budgets.map((budget) => {
            const amount = getBudgetExpense(budget.id).reduce(
              (total, expense) => total + expense.amount,
              0
            );
            return (
              <Cards
                key={budget.id}
                onAddExpenseClick={() => openAddExpenseModal(budget.id)}
                onViewExpensesClick={() => openViewExpenseModal(budget.id)}
                name={budget.name}
                amount={amount}
                max={budget.max}
              />
            );
          })}
          <TotalBudgetCard />
        </div>
        <Modal showModal={showModal} setShowModal={setShowModal} />
        <ExpenseModal
          defaultBudgetId={addExpenseModalBudgetId}
          showExpenseModal={showExpenseModal}
          setShowExpenseModal={setShowExpenseModal}
        />
        <ViewExpensesModal
          budgetId={viewExpensesModalBudgetId}
          showViewModal={showViewModal}
          setShowViewModal={setShowViewModal}
        />
      </div>
    </>
  );
}
